title: <p align="center"> Prasanna Rahavendra A </p>
logo: /assets/img/prasanna.jpg

description: <p align="center">
  <a href="https://www.linkedin.com/in/prasanna-rahavendra">LinkedIn</a> |
  <a href="https://github.com/Prasanna2000">GitHub</a>

  <br>
  I am working as a software developer in VISA Inc. Bangalore.
  I work in the full stack domain, specalizing in Angular, Java Spring Boot, MongoDB, SQL, Kafka, Docker, k8s, etc.,
  <br>
  </p>

theme: jekyll-theme-minimal
